stages:
  - build-app
  - test
  - build-docker

cache:
  paths:
    - node_modules/

build-app:
  image: node:latest
  stage: build-app
  script:
    - npm ci

test:
  image: node:latest
  stage: test
  script:
    - npm test
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/

build-docker:
  services:
    - docker:18-dind
  image: docker:19.03.12
  before_script:
    - echo "$GITLAB_REGISTRY_PASS" | docker login -u "$GITLAB_REGISTRY_USER" --password-stdin "$GITLAB_REGISTRY_URL"
  stage: build-docker
  script:
    - docker build -t registry.gitlab.com/collinear/kudobot .
    - docker push registry.gitlab.com/collinear/kudobot
